/** Curated prompt text. Kept separate from picker/filtering logic for easy editing. */

export const GO_HOME_DARE =
	"Go home—only if you genuinely want to and have a safe way home. Otherwise, pass or sit out the next round.";

export const KENYAN_PROMPTS = {
	neutral: {
		truth: [
			"Which Kenyan meal could you happily eat every day for a week?",
			"Which county, apart from your home county, would you choose for a free weekend, and why?",
			"Which Kiswahili, Sheng, or local-language phrase do you use the most?",
			"What is one matatu song that instantly takes you back to a specific time?",
			"Which Kenyan snack do you always buy when you spot it?",
			"What is your favourite thing about visiting shags or your family home?",
			"Which Kenyan town has the best weather for you?",
			"When has M-PESA made your day much easier?",
			"How do you take your chai, and what must be served with it?",
			"What is your dream Kenyan road-trip route?",
			"Which school-day tradition in Kenya do you remember most clearly?",
			"What local market, café, kibanda, or hangout would you recommend to everyone here?",
			"What Kenyan celebration or family gathering do you always look forward to?",
			"What does your ideal Kenyan Saturday look like from morning to night?",
			"Which Kenyan language would you love to speak more fluently?",
		],
		dare: [
			"Name five Kenyan counties in ten seconds.",
			"Explain how to make ugali as if you are hosting a serious TV cooking show.",
			"Compliment the player to your right in Kiswahili, Sheng, or another Kenyan language, then translate it.",
			"Sing one clean line from a Kenyan song the group knows.",
			"Read an imaginary M-PESA confirmation message in your best official voice.",
			"Give directions to your favourite place using Kenyan landmarks only—no street names.",
			"Present tomorrow's weather for any three Kenyan counties like a TV presenter.",
			"Teach the group a greeting from a Kenyan language you know and explain its meaning.",
			"Recommend your favourite Kenyan snack like it is a five-star meal.",
			"Plan a three-stop Kenyan road trip in twenty seconds.",
			"Name six Kenyan foods in ten seconds without repeating a dish.",
			"Teach the group one harmless Sheng word and use it in a sentence.",
			"Commentate someone pouring chai like it is a major football final.",
			"Mime making tea and mandazi until the group guesses both.",
			"Call every player “Mheshimiwa” until your next turn.",
		],
	},
	funny: {
		truth: [
			"Have you ever said “niko karibu” while you were still in the house? How far were you really?",
			"What is the funniest excuse you have ever blamed on KPLC or the network?",
			"Have you ever seen an M-PESA request and pretended you did not? What happened?",
			"What is your funniest or most embarrassing matatu story?",
			"Have you ever carried food home from a function? Be honest about how much.",
			"What is the most ridiculous nickname you have had at home or school?",
			"Which Sheng word have you confidently used the wrong way?",
			"What is the smallest amount you have ever tried to bargain down?",
			"Have you ever gone to a Kenyan wedding mainly for the food?",
			"What harmless school rule or assembly moment can you laugh about now?",
			"Have you ever missed your stage and acted as if that was the plan?",
			"What is the most dramatic way a Kenyan parent or relative has called your name?",
			"Which person here is most likely to say “five minutes” and arrive an hour later?",
			"What is your funniest failed attempt at speaking a Kenyan language?",
			"What is the strangest question a relative has asked you at a family gathering?",
		],
		dare: [
			"Say “niko karibu” in five different emotions.",
			"Give your best matatu tout impression for ten seconds without touching anyone.",
			"Act like a Kenyan parent calling a child by all three names.",
			"Advertise an object nearby like it is the hottest bargain at Gikomba.",
			"Give a campaign speech for why you should be elected President of Vibes.",
			"Report everything happening in the room like a Kenyan TV news anchor.",
			"Pretend your M-PESA balance is KSh 13 and convince the group you are still rich.",
			"Imitate a sports commentator narrating a matatu race that exists only in your imagination.",
			"Defend ugali or chapati like it is a live national debate.",
			"Dance to an imaginary gengetone, kapuka, or Kenyan pop beat for fifteen seconds.",
			"Pretend the network is breaking while you explain why you are late.",
			"Welcome the group like an overexcited Kenyan wedding MC.",
			"Act out the exact moment the lights return after a blackout.",
			"Celebrate an imaginary Harambee Stars winning goal in slow motion.",
			"Give a ten-second weather report using as much harmless Sheng as you can.",
		],
	},
	deep: {
		truth: [
			"What part of growing up in Kenya shaped you the most?",
			"When you say “home,” which place, people, sounds, or smells do you mean?",
			"Which value from your family or community do you want to carry forward?",
			"What sacrifice made by someone in your family do you understand better now?",
			"Which expectation about school, work, marriage, or success have you had to question?",
			"How do you balance helping family with protecting your own needs?",
			"What part of your language or culture are you proudest to share?",
			"What has the Kenyan hustle taught you about friendship or resilience?",
			"What gives you genuine hope about Kenya's future?",
			"Who stood by you during a difficult season, and what did they do?",
			"How has your definition of a good life changed as you have grown?",
			"Which Kenyan tradition would you like the next generation to keep?",
			"What boundary with relatives or friends took courage for you to set?",
			"What does success mean to you beyond money, titles, and pressure?",
			"What would you tell your younger self growing up here about belonging?",
		],
		dare: [
			"Share a proverb from any Kenyan language and explain what it means to you.",
			"Thank someone here for one specific way they have shown up for you.",
			"Say one honest hope you carry for Kenya's next generation.",
			"Describe one family or community tradition you want to preserve.",
			"Share a life lesson you learned from a parent, guardian, teacher, or elder.",
			"Offer one sincere sentence of encouragement to anyone facing the job hunt or hustle.",
			"Name one strength your community gave you that you sometimes forget.",
			"Describe the Kenyan place where you feel most peaceful and explain why.",
			"Name one small step you can take this week toward a goal you keep postponing.",
			"Name three small things that make you feel at home, without explaining them.",
			"Give a specific, character-based compliment to the quietest willing player.",
			"Finish this sentence honestly: “I am learning that I do not have to…”",
			"Name one promise you want to keep to your future self.",
			"Give a short appreciation message to Kenyan workers whose effort often goes unnoticed.",
			"Take one quiet breath, then name an ordinary thing you are grateful for today.",
		],
	},
	couples: {
		truth: [
			"Which Kenyan song best tells the story of your relationship?",
			"What simple Kenyan date—nyama choma, a walk, chai, or something else—would make you happiest?",
			"Which county would you choose for your next trip together, and why?",
			"What did your partner do that made meeting friends or family feel easier?",
			"Which Kenyan meal best matches your partner's personality?",
			"Which word from Kiswahili, Sheng, or your home language best describes your love?",
			"How can your partner support you when the hustle becomes exhausting?",
			"What money conversation would help the two of you understand each other better?",
			"Which small public or private sign of affection makes you feel chosen?",
			"What Sunday or weekend ritual would you love to build together?",
			"Which family or cultural tradition would you like to share as a couple?",
			"What Kenyan trip, function, or ordinary day gave you a favourite memory together?",
			"What has traffic, distance, or busy schedules taught you about making time for love?",
			"Which quality in your partner—warmth, resilience, generosity, or something else—reminds you most of home?",
			"If you could build a future home anywhere in Kenya, where would it be?",
		],
		dare: [
			"Dedicate a Kenyan love song to your partner and explain why you chose it.",
			"Plan a thoughtful date in Kenya on a KSh 1,500 budget without using a calculator.",
			"Tell your partner “I love you” in Kiswahili or another Kenyan language you know.",
			"Ask your partner to slow-dance while you hum a Kenyan song; continue only if they agree.",
			"Introduce your partner like a radio host dedicating the next song to them.",
			"Give your partner a sweet compliment using a little Kiswahili or harmless Sheng.",
			"Recreate your first hello to each other as dramatically as possible.",
			"Plan a two-day Kenyan getaway together in thirty seconds.",
			"Create a private couple handshake, provided you both want one.",
			"Invent a funny slogan for your relationship and say it together.",
			"Settle this lovingly: who makes better chai, and why?",
			"Describe your partner as a Kenyan destination without naming the destination.",
			"Give your partner a ten-second acceptance speech for “Best Teammate.”",
			"Send no message—just compose a one-line radio dedication to your partner and read it aloud.",
			"Ask your partner if they would like a twenty-second hug; respect their answer completely.",
		],
	},
	bold: {
		truth: [
			"What is your most unpopular Kenyan food opinion?",
			"Which famous Kenyan song or artist do you secretly not enjoy?",
			"What is the boldest first move you have made after meeting someone at a function or night out?",
			"Who here would survive a chaotic CBD errand best, and why?",
			"Which willing player made a strong first impression on you, and what was kind or surprising about it?",
			"What is the biggest excuse you have given family to protect your plans?",
			"Which career or life choice would you make if nobody in the family could judge it?",
			"When did you last speak up in public even though your heart was racing?",
			"What is one thing on your camera roll you would need to explain before showing it?",
			"Have you ever had a crush on someone at a wedding, chama, church, campus, or work function?",
			"Which post, status, or tweet did you delete because it was too honest?",
			"What is the most painful amount you have spent impulsively through M-PESA?",
			"Who in this group would you trust to take you on an unplanned Kenyan road trip?",
			"Which Kenyan town would you disappear to for a month if responsibilities paused?",
			"What hustle or side-business attempt failed but taught you something useful?",
		],
		dare: [
			GO_HOME_DARE,
			"Freestyle for fifteen seconds using the words Kenya, matatu, chapati, and M-PESA.",
			"Do a runway walk like you are headlining Nairobi Fashion Week.",
			"Give a ten-second speech accepting your new title as Chairperson of Good Vibes.",
			"Deliver your smoothest Kiswahili or Sheng pickup line to an imaginary person.",
			"Dance confidently to a Kenyan song chosen by the group for fifteen seconds.",
			"Describe yourself like a slogan painted on the back of a matatu.",
			"Perform your wildest football goal celebration without touching anyone.",
			"State your unpopular Kenyan food opinion and defend it for twenty seconds.",
			"Sing the chorus of a Kenyan song as if you are closing a sold-out concert.",
			"Pitch an imaginary M-PESA loan product that nobody should realistically accept.",
			"Enter the room again like a Kenyan celebrity arriving at JKIA.",
			"Challenge a willing player to a ten-second staring contest.",
			"Tell the group your first impression of this game with complete honesty.",
			"Act like a Safari Rally navigator calling out impossible directions for fifteen seconds.",
		],
	},
	naughty: {
		truth: [
			"What is the boldest late-night “uko?” text you have sent to another consenting adult?",
			"Which Kenyan song puts you in a sexy mood immediately?",
			"Would your ideal adult getaway be in Diani, Naivasha, Nanyuki, or somewhere else—and what happens after the door closes?",
			"What is the riskiest place where you have kissed another consenting adult?",
			"What is the most explicit sext you have sent or wanted to send?",
			"Which outfit or piece of lingerie makes you feel most desirable?",
			"Which Kiswahili, Sheng, or local-language pet name sounds sexiest to you?",
			"How do you like a consenting adult partner to begin foreplay?",
			"What private fantasy would you choose for a child-free, phone-off weekend in Kenya?",
			"What kind of voice, phrase, or way of speaking do you find most attractive?",
			"What would your perfect adults-only night in include from music to aftercare?",
			"Do you prefer subtle public flirting or intense private attention, and why?",
			"What is the most daring thing you have done after a Kenyan house party or night out?",
			"Which sexual boundary are you proud of communicating clearly?",
			"What role-play or power dynamic are you curious about exploring with a consenting adult?",
		],
		dare: [
			"Say “uko?” in the most seductive voice you can manage.",
			"Create a flirty one-liner using Kiswahili or Sheng and deliver it to an imaginary adult crush.",
			"Describe your ideal adults-only weekend in Diani or Naivasha, including one firm boundary.",
			"Perform a ten-second sensual dance while fully clothed and without touching anyone.",
			"Ask a willing adult player if they want to hear a sexy compliment; give one only after a clear yes.",
			"Write nothing—say the three-word sexy text you would send to a consenting adult partner.",
			"Give one clear, confident example of how you would ask for consent before a kiss.",
			"Dedicate a Kenyan love song to an imaginary late-night lover in your smoothest radio voice.",
			"Ask a willing adult player for five seconds of flirty eye contact; stop immediately if they decline.",
			"Describe your ideal kiss in one explicit but respectful sentence without acting it out.",
			"Choose a sexy Kiswahili, Sheng, or local-language nickname for yourself for one round.",
			"Give yourself one confident, body-positive compliment out loud.",
			"Say one line of consensual dirty talk you would be comfortable using with an adult partner.",
			"Describe one sexual fantasy and the boundary that would make it feel safe.",
			"Hold a five-second seductive pose while fully clothed, then take a theatrical bow.",
		],
	},
};
