/** Curated prompt text with exact duplicates removed. */

export const GO_HOME_DARE = "Go home.";
export const DARE_ANYONE_HOME = "Dare anyone here to go home.";

const truth = [
	"Have you ever had a crush on a friend's partner?",
	"What's the most embarrassing thing you've done in front of someone you like?",
	"What's the craziest thing you've ever done to get someone's attention?",
	"Have you ever secretly checked someone's phone without them knowing?",
	"What's a secret you've never told anyone?",
	"Have you ever lied to get out of a date?",
	"What's the most awkward date you've ever been on?",
	"Who in this room would you most want to kiss?",
	"Have you ever had a romantic dream about someone in this room?",
	"What's the most trouble you've ever gotten into?",
	"What's the worst date you've ever been on?",
	"Have you ever cheated on a test?",
	"What's the biggest lie you've ever told?",
	"Have you ever been caught doing something you shouldn't have been doing?",
	"What's the most ridiculous thing you've done to impress someone?",
	"Have you ever pretended to like a gift you hated?",
	"What's the most embarrassing thing you've posted online?",
	"Have you ever ghosted someone?",
	"What's the most daring thing you've done on a dare?",
	"Have you ever stolen anything?",
	"What's the most embarrassing thing your parents have caught you doing?",
	"Have you ever flirted with someone to get something you wanted?",
	"What's the most awkward thing you've said to someone you liked?",
	"Have you ever had a crush on a teacher or professor?",
	"What's the weirdest thing you've ever done in front of a mirror?",
	"What's the most embarrassing thing you've ever done on a date?",
	"Have you ever had a crush on someone inappropriate?",
	"What's the biggest lie you've ever told someone you care about?",
	"Have you ever stalked someone on social media?",
	"What's the most awkward thing you've said during a romantic moment?",
	"What's a secret you've kept from your best friend?",
	"What's the most daring thing you've done in public?",
	"What's your guilty pleasure that you'd be embarrassed to admit?",
	"Have you ever been caught in a lie?",
	"What's the most scandalous photo you've ever sent to someone?",
	"Have you ever pretended to like a gift just to be polite?",
	"What's a habit you have that would surprise others?",
	"Have you ever flirted with someone else while in a relationship?",
	"Have you ever shared a secret you promised to keep?",
	"What's the most trouble you've gotten into at school or work?",
	"What's the most awkward encounter you've had with a stranger?",
	"What's something you've done that you'd never admit to your parents?",
	"Have you ever lied to get out of a social obligation?",
	"Have you ever ghosted someone you were talking to?",
	"What's the biggest risk you've taken in your love life?",
	"Who's your most recent stalk on IG?",
	"What's one thing you've lied to your parents about recently?",
	"Who would you never date in this room and why?",
	"What's a secret you're taking to the grave (until now)?",
	"If you were arrested right now, what would your friends assume it was for?",
	"Who in this room would you call first if you needed to hide a body — and why?",
	"What's the wildest thing you've done that your parents still don't know about?",
	"what's something you've googled in secret and would die if someone found out?",
	"If you had to rate your flirting skills from 1 to 10, what's your honest score and why?",
	"Would you rather your partner be overly jealous or not jealous at all? Why?",
	"If your crush confessed they liked someone else, would you help them or sabotage it?",
	"What's the most manipulative thing you've done to get what you wanted?",
	"What's something you've done that you'd never admit to in person?",
	"What's the one lie you've told that spiraled out of control?",
	"If you had to kiss one person in this room, who would it be and why?",
	"What's the most embarrassing thing you've done to get someone's attention?",
	"If you had to delete all but 3 apps on your phone, which would you keep and why?",
	"What's the most childish thing you still do?",
	"If you could know one truth about anyone in this room, what would it be?",
];

const dare = [
	"Send a flirty message to the third contact in your phone.",
	"Post a silly selfie on your social media.",
	"Let someone in the group send a message to anyone in your contact list.",
	"Change your social media profile picture to the first photo in your camera roll for 24 hours.",
	"Let someone in the group send anything they want to the last person you messaged.",
	"Text your crush and tell them you have feelings for them.",
	"Call a random person and just bark.",
	"Cut off a piece of your hair.",
	"Tell the person to your left something you don't like about them.",
	"Eat a spoonful of hot sauce.",
	"Share the last picture you took on your phone.",
	"Let someone go through your YouTube history and read it out loud.",
	"Whisper a secret to the person on your left.",
	"Show the most embarrassing photo on your phone.",
	"Reply something controversial to the first Instagram stories on your timeline",
	"Call a random contact and sing “Twinkle, Twinkle, Little Star” to them.",
	"Let someone draw a tattoo on you with a marker.",
	"Let someone post anything they want on your instagram or tiktok.",
	"Show your google search history.",
	"Let someone text anyone from your contacts and they can write whatever they want.",
	"Like 20 pictures of your ex's instagram posts.",
	"Call your mom and tell her you want to be a dog.",
	"Let someone in the group read the last text message you sent out loud.",
	"Text your ex “I miss you” and don't explain.",
	"Do your worst celebrity impression right now.",
	"Let someone go through your camera roll for 10 seconds.",
	"Read your last 3 texts out loud.",
	"Text your crush ‘we need to talk’... then put your phone face down for 10 minutes.",
	"Post an unhinged (but vague) message on your story like: “I can't keep this a secret any longer...”",
	"Text your crush “It's done. The body is buried.” and don't reply for 10 minutes.",
	"Speak only in meows or barks for the next 3 minutes.",
	"Change your status to ‘Looking for trouble’ and leave it for an hour.",
	"Call your crush and ask if they're jealous of your ex, right now.",
	"Call a friend and confess something you've been hiding from them, but in a song",
	"Let someone else go through your phone for one minute, no limits.",
	"Let the group choose an embarrassing outfit for you to wear for the next hour.",
	"Let the group choose an embarrassing status for you to post for an hour",
	"Post a selfie with the caption ‘Convince me not to delete this.’",
	"Speak in a movie-trailer voice until your next turn.",
	"Balance a book or another light, unbreakable object on your head for 30 seconds.",
	"Perform three animal impressions and let the group guess each one.",
	"Invent a handshake with a willing player.",
	"Give a dramatic reading of the label on the nearest snack or drink.",
	"Freeze like a statue until the next player finishes their turn.",
	"Do a runway walk across the room using the silliest pose you can invent.",
	"Sing one chorus in an opera voice.",
	"Tell your corniest joke with a completely serious face.",
	"Draw a self-portrait with your eyes closed in 30 seconds.",
	"Let the group give you a harmless nickname for the next three rounds.",
	"Act out an emoji chosen by the group without making a sound.",
	"Perform a 20-second air-guitar solo.",
	"Spell your first name using only body movements.",
	"Mime a household chore until someone guesses it.",
	"Give a 30-second acceptance speech for “Most Dramatic Player.”",
	"Avoid saying the letter E until your next turn.",
	"Give every player a sincere compliment in five words or fewer.",
	"Silently recreate a famous movie scene until someone guesses it.",
	"Make a 20-second commercial for a harmless object in the room.",
	"Balance a spoon on your nose for 15 seconds.",
	"Tell a story that includes five words chosen by the group.",
	"Draw an animal with your non-dominant hand and let the group guess it.",
	"Create a four-line rap about this game.",
	"Mime crossing a finish line in slow motion from where you are.",
	"Keep a straight face for 30 seconds while the group tries to make you laugh without touching you.",
	"Narrate your own actions like a wildlife documentary until your next turn.",
	"Answer the next question entirely in rhyme.",
	"Pretend you are royalty and address the group for 30 seconds.",
	"Perform a weather report about the room.",
	"Make sound effects for a willing player as they take five steps.",
	"Invent one silly dance move and teach it to the group.",
	"Act like the floor is lava for 15 seconds without climbing on furniture.",
	"Move and speak like a robot until your next turn.",
	"Say the alphabet backward as far as you can in 20 seconds.",
	"Give each player a respectful superhero name and power.",
	"Give a passionate 30-second speech about why forks are better than spoons.",
	"Speak only in questions until your next turn.",
	"Pose as a museum statue and let the group name the artwork.",
	"Sing your favorite meal order like a dramatic ballad.",
	"Use your non-dominant hand for ordinary tasks until your next turn, where practical.",
	"Stack three light, unbreakable objects in 30 seconds.",
	"Act out missing a bus without speaking.",
	"Interview your imaginary alter ego for 30 seconds.",
	"Make a tongue twister from your first name and say it three times.",
	"Describe a favorite movie without its title or character names until someone guesses it.",
	"Mirror a willing player's movements for 20 seconds.",
	"Give your best villain laugh, then say a normal sentence without laughing.",
	"Sketch a mascot for the group in 45 seconds.",
	"Make a superhero entrance with an imaginary cape.",
	"Pretend to have a phone call with yourself ten years in the future.",
	"Speak like a pirate until your next turn.",
	"Perform five exaggerated facial expressions chosen by the group.",
	"Create a short rhythm by clapping or tapping and have the group repeat it.",
	"Spell a word chosen by the group backward.",
	"Make a shadow puppet and let the group guess what it is.",
	"Act out your morning routine in 20 seconds.",
	"Introduce the player to your right as a fantasy hero with a respectful title.",
	"Reenact your last trip to a shop as a silent action movie.",
	"Make up a two-line theme song for the player chosen by the group.",
	"Give a 20-second cooking-show demonstration using an imaginary ingredient.",
	"Make up a new holiday and explain its strangest tradition.",
	"Speak as if everything is breaking news until your next turn.",
	"Create a slogan for the group and lead everyone in saying it once.",
	"Explain how to make toast as if you are directing a space mission.",
	"Train an imaginary pet to do one impressive trick.",
	"Give sports commentary while a willing player performs an ordinary action.",
	"Describe your favorite color without naming it until someone guesses it.",
	"Invent a new word, define it, and use it in a sentence.",
	"Give a motivational speech to an object that has given up.",
	"Act as a tour guide for the room for 30 seconds.",
	"Retell your day in reverse order in 30 seconds.",
	"Give yourself a secret-agent codename and explain your signature gadget.",
	GO_HOME_DARE,
	DARE_ANYONE_HOME,
];

const naughtyTruth = [
	"Do you masturbate, and how often do you honestly do it?",
	"What's your body count? You can give an exact number or a range.",
	"If every adult involved were single and consenting, would you give oral sex to the person next to you?",
	"Do you prefer giving or receiving oral sex, and why?",
	"What's your favorite sex position, and what makes it your favorite?",
	"Have you ever faked an orgasm? What made you fake it?",
	"When was your last orgasm, and was it solo or with a partner?",
	"What kind of porn or erotic content turns you on most?",
	"Have you ever sent a nude or an explicit sext? Did you regret it?",
	"Have you ever had a one-night stand? Would you do it again?",
	"Have you ever had a friends-with-benefits arrangement? How did it end?",
	"What's the riskiest place you've actually had consensual sex?",
	"Have you ever been caught masturbating or having sex? What happened?",
	"Do you own a sex toy, or which one would you most like to try?",
	"In bed, are you more dominant, submissive, or a switch?",
	"Would you ever have a consensual threesome, and what would your ground rules be?",
	"What's the kink or fetish you're most curious to explore with a consenting partner?",
	"Have you ever had a sexual fantasy about another adult in this room? Keep it anonymous unless they agree to be named.",
	"Are you usually loud or quiet during sex, and has anyone ever commented on it?",
	"What's one piece of dirty talk that instantly turns you on?",
	"Have you ever stopped a sexual encounter because protection or clear consent was missing?",
	"What's the shortest time you've known someone before consensually hooking up with them?",
	"Which consensual hookup do you regret most, and why?",
	"What would you rate your bedroom skills out of ten, and what skill earned that score?",
	"What's one sexual boundary that no amount of attraction could make you cross?",
];

const naughtyDare = [
	"Roll your tongue in a slow, seductive circle while holding your best bedroom stare for ten seconds.",
	"Seduce the willing adult on your left for 30 seconds using only words and body language; do not touch them.",
	"Twerk for 45 seconds like you're auditioning for an adults-only music video.",
	"Give a seductive 45-second dance to any song chosen by the willing adult on your right, staying fully clothed.",
	"Do five slow body rolls while naming five things that turn you on.",
	"Use a sturdy chair as an imaginary pole and perform a 30-second pole dance without climbing on it.",
	"Give a willing adult a 20-second fully clothed lap dance, staying contact-free unless you both explicitly agree otherwise.",
	"Perform a 30-second burlesque routine while keeping every item of clothing on.",
	"Mime an outrageously slow striptease using only imaginary clothes; remove nothing real.",
	"Remove one optional outer layer, or keep it on and strike your boldest bedroom pose instead.",
	"Walk across the room as if you're entering a bedroom where your consenting fantasy partner is waiting.",
	"Do a dramatic morning-after walk-of-shame runway, complete with a guilty smile.",
	"Give the group ten seconds of bedroom eyes, a slow lip bite, and your most shameless wink.",
	"Without speaking, perform the clearest 'come to bed with me' gesture you can invent.",
	"Let the group choose an innocent phrase and say it in three increasingly sexual tones.",
	"Read the label on the nearest snack as if you're recording an explicit phone-sex message.",
	"Whisper one explicit line of dirty talk to a willing adult from a respectful distance; no touching.",
	"Deliver a 30-second dirty-talk monologue to an imaginary consenting lover.",
	"Say your own name with your most convincing bedroom moan.",
	"Perform an exaggerated five-second fake orgasm while staying fully clothed and touching nobody.",
	"Demonstrate your ideal kissing technique using only the back of your own hand.",
	"Explain your best oral-sex technique using words and hand gestures only; do not touch any person or object.",
	"Spell the word 'SEX' with your hips while the group guesses the letters.",
	"Act out your favorite sex position as a solo, fully clothed silhouette without touching anyone.",
	"Make a 20-second adults-only commercial for condoms that is equal parts sexy and responsible.",
	"Demonstrate how you would ask for consent in the sexiest possible voice while still making the question unmistakably clear.",
	"Role-play negotiating a kink with an imaginary partner, including one boundary and a safe word.",
	"Choose a safe word and work it naturally into a filthy one-liner.",
	"Say 'slower,' 'harder,' and 'stop' as three clear bedroom instructions, making the last one instantly serious.",
	"Review an imaginary sex toy in a breathless 30-second commercial without using a real object.",
	"Invent a ridiculous new adult toy, name it, and pitch its features to the group.",
	"Model an imaginary set of lingerie in a fully clothed bedroom runway walk.",
	"Strike three different fully clothed poses for an imaginary adults-only magazine cover.",
	"Create your boldest thirst-trap pose for ten seconds, but do not take or post a photo.",
	"Give step-by-step instructions for your ideal sensual massage without touching anyone.",
	"Give a willing adult a 20-second shoulder massage over clothing, or perform the motions in the air if they decline.",
	"Recreate the moment before a kiss with a willing adult, stopping a full hand's width apart with no contact.",
	"Ask a willing adult to choose a blown kiss, a hand kiss, or no kiss; make contact only after a clear yes.",
	"Hold eye contact with a willing adult for 20 seconds while admitting your biggest turn-on in one sentence.",
	"Tell a willing adult one respectful feature of theirs that would distract you in a bedroom; they may decline to participate.",
	"Describe one consensual sexual fantasy to a willing adult on your left; they only have to listen if they opt in.",
	"Deliver your boldest pickup line involving a bed to a willing adult without moving closer to them.",
	"Show, without words, how you would invite an imaginary consenting lover back to your bedroom.",
	"Act out greeting an imaginary secret lover at a hotel door, ending the scene before any contact.",
	"Role-play instant sexual chemistry with a willing adult for 30 seconds, fully clothed and completely contact-free.",
	"Let a willing adult choose dirty compliment, intense eye contact, or seductive one-liner, then deliver only that choice.",
	"Recreate a steamy romance-novel cover with a willing adult, fully clothed and using only contact you both explicitly approve.",
	"Make a dominant bedroom entrance, then repeat it as a shy submissive entrance; touch nobody.",
	"Say 'Tell me what you want' once in a dominant voice and once in a submissive voice.",
	"Deliver a filthy toast to great sex, clear consent, and terrible decisions.",
	"Create a two-line erotic poem using two harmless words chosen by the group.",
	"Improvise a 30-second steamy romance scene with an imaginary lover and end it by announcing 'cut to black.'",
	"Narrate an imaginary consensual hookup like a wildlife documentary for 30 seconds.",
	"Describe the first minute after you and an imaginary consenting lover close the bedroom door, stopping before any sex act.",
	"Give an imaginary lover 20 seconds of explicit bedroom instructions without acting any of them out.",
	"Pantomime pausing a heated hookup to reach for protection and ask for consent.",
	"Demonstrate three genuinely sexy ways to ask 'May I kiss you?' without kissing anyone.",
	"Turn three safe-sex rules into the sultriest public-service announcement the group has ever heard.",
	"Design the outfit you would wear for an adult fantasy, describe every detail, and give the look a name.",
	"Act out the title of a famous steamy movie using only adult charades until someone guesses it.",
	"Perform your most dramatic reaction to being caught masturbating, with no actual undressing or touching.",
	"Mime trying to retrieve a hidden sex toy from a squeaky drawer without waking an imaginary roommate.",
	"Give a 20-second acceptance speech for winning 'Best Lover of the Year.'",
	"Boast for 20 seconds about why an imaginary ex still misses your bedroom skills.",
	"Roast your own sexual technique for ten seconds, then hype it up for another ten.",
	"Confess your dirtiest recent thought aloud, leaving out any real person's identity.",
	"Give the group a brutally honest three-item checklist for earning a second night with you.",
	"Rank oral sex, kissing, dirty talk, and massage from favorite to least favorite, then defend your top choice.",
	"Answer quickly: lights on or off, top or bottom, slow or rough, silent or loud, morning or night.",
	"Pretend to eat an imaginary strawberry in the most indecently seductive way possible.",
	"Mime tracing an ice cube slowly along your own forearm while maintaining bedroom eye contact with the group.",
	"Perform a 20-second shower-seduction scene while fully clothed, alone, and touching nobody.",
	"Act out waking beside an imaginary one-night stand and suddenly remembering you are late for work.",
	"Give an imaginary partner a sincere 20-second aftercare speech following an intense consensual night.",
	"State one firm sexual boundary in the same seductive tone you would use to state a turn-on.",
	"React as seductively as possible to the line 'I have roommates and the walls are thin.'",
	"Create a five-beat rhythm made entirely from exaggerated bed-squeak sound effects.",
	"Define the word 'orgasm' like a very flustered professor giving a serious lecture.",
	"Explain foreplay from start to finish using only a cooking-show metaphor.",
	"Give a dramatic weather forecast for a night of consensual sex, including heat, moisture, and a safe ending.",
	"Campaign for lights-on sex in a 20-second speech, then argue just as passionately for lights-off sex.",
	"Demonstrate removing an imaginary bra one-handed while remaining completely dressed.",
	"Teach the group how to put on an imaginary condom using only clean hand gestures and no props.",
	"Create a 20-second spanking rhythm on your own clothed thigh, then turn it into a dance beat.",
	"Command an imaginary consenting lover to kneel using your strongest dominant voice, then thank them for checking in.",
	"Beg an imaginary consenting lover for more in the most shameless voice you can manage.",
	"Give three explicit compliments to your own body while holding a confident bedroom pose.",
	"Describe how you would tease an imaginary consenting partner without touching them, in three escalating steps.",
	"Act out your reaction to receiving an unexpectedly excellent consensual nude, without using a phone.",
	"Compose a graphic two-sentence sext aloud for an imaginary partner; do not type or send it.",
	"Read the sentence 'I'll be there in ten minutes' as if it were the dirtiest sext you've ever received.",
	"Give a 20-second tutorial on the difference between sexy confidence and ignoring consent.",
	"Name three bedroom turn-ons while slowly tracing a heart over your own clothes with one finger.",
	"Name three instant sexual turn-offs in your most seductive voice without laughing.",
	"Pretend you said the wrong name in bed and spend 20 seconds trying to talk your way out of it.",
	"Describe your ideal post-sex breakfast as if it is the climax of an erotic novel.",
	"Perform a solo, fully clothed charade of 'quickie,' 'one-night stand,' or 'morning after' and let the group guess which.",
	"Give a willing adult a choice between your dirtiest wink, your filthiest one-liner, or your best bedroom stare; respect their choice.",
	"Finish the sentence 'The sexiest thing a consenting partner could whisper to me is...' and perform the line.",
	"End with a 30-second adults-only cabaret combining a tongue roll, body roll, bedroom stare, and dramatic final pose.",
];

export const CURATED_PROMPTS = Object.freeze({
	photos: Object.freeze({
		truth: Object.freeze(truth),
		dare: Object.freeze(dare),
	}),
	naughty: Object.freeze({
		truth: Object.freeze(naughtyTruth),
		dare: Object.freeze(naughtyDare),
	}),
});
