/** Curated prompt text with exact duplicates removed. */

export const GO_HOME_DARE = "Go home.";
export const DARE_ANYONE_HOME = "Dare anyone here to go home.";

const truth = [
	"Have you ever had a crush on a friend's partner?",
	"What's the most embarrassing thing you've done in front of someone you like?",
	"What's the craziest thing you've ever done to get someone's attention?",
	"Have you ever secretly checked someone's phone without them knowing?",
	"What's a secret you've never told anyone?",
	"Have you ever lied to get out of a date?",
	"What's the most awkward date you've ever been on?",
	"Who in this room would you most want to kiss?",
	"Have you ever had a romantic dream about someone in this room?",
	"What's the most trouble you've ever gotten into?",
	"What's the worst date you've ever been on?",
	"Have you ever cheated on a test?",
	"What's the biggest lie you've ever told?",
	"Have you ever been caught doing something you shouldn't have been doing?",
	"What's the most ridiculous thing you've done to impress someone?",
	"Have you ever pretended to like a gift you hated?",
	"What's the most embarrassing thing you've posted online?",
	"Have you ever ghosted someone?",
	"What's the most daring thing you've done on a dare?",
	"Have you ever stolen anything?",
	"What's the most embarrassing thing your parents have caught you doing?",
	"Have you ever flirted with someone to get something you wanted?",
	"What's the most awkward thing you've said to someone you liked?",
	"Have you ever had a crush on a teacher or professor?",
	"What's the weirdest thing you've ever done in front of a mirror?",
	"What's the most embarrassing thing you've ever done on a date?",
	"Have you ever had a crush on someone inappropriate?",
	"What's the biggest lie you've ever told someone you care about?",
	"Have you ever stalked someone on social media?",
	"What's the most awkward thing you've said during a romantic moment?",
	"What's a secret you've kept from your best friend?",
	"What's the most daring thing you've done in public?",
	"What's your guilty pleasure that you'd be embarrassed to admit?",
	"Have you ever been caught in a lie?",
	"What's the most scandalous photo you've ever sent to someone?",
	"Have you ever pretended to like a gift just to be polite?",
	"What's a habit you have that would surprise others?",
	"Have you ever flirted with someone else while in a relationship?",
	"Have you ever shared a secret you promised to keep?",
	"What's the most trouble you've gotten into at school or work?",
	"What's the most awkward encounter you've had with a stranger?",
	"What's something you've done that you'd never admit to your parents?",
	"Have you ever lied to get out of a social obligation?",
	"Have you ever ghosted someone you were talking to?",
	"What's the biggest risk you've taken in your love life?",
	"Who's your most recent stalk on IG?",
	"What's one thing you've lied to your parents about recently?",
	"Who would you never date in this room and why?",
	"What's a secret you're taking to the grave (until now)?",
	"If you were arrested right now, what would your friends assume it was for?",
	"Who in this room would you call first if you needed to hide a body — and why?",
	"What's the wildest thing you've done that your parents still don't know about?",
	"what's something you've googled in secret and would die if someone found out?",
	"If you had to rate your flirting skills from 1 to 10, what's your honest score and why?",
	"Would you rather your partner be overly jealous or not jealous at all? Why?",
	"If your crush confessed they liked someone else, would you help them or sabotage it?",
	"What's the most manipulative thing you've done to get what you wanted?",
	"What's something you've done that you'd never admit to in person?",
	"What's the one lie you've told that spiraled out of control?",
	"If you had to kiss one person in this room, who would it be and why?",
	"What's the most embarrassing thing you've done to get someone's attention?",
	"If you had to delete all but 3 apps on your phone, which would you keep and why?",
	"What's the most childish thing you still do?",
	"If you could know one truth about anyone in this room, what would it be?",
];

const dare = [
	"Send a flirty message to the third contact in your phone.",
	"Post a silly selfie on your social media.",
	"Let someone in the group send a message to anyone in your contact list.",
	"Change your social media profile picture to the first photo in your camera roll for 24 hours.",
	"Let someone in the group send anything they want to the last person you messaged.",
	"Text your crush and tell them you have feelings for them.",
	"Call a random person and just bark.",
	"Cut off a piece of your hair.",
	"Tell the person to your left something you don't like about them.",
	"Eat a spoonful of hot sauce.",
	"Share the last picture you took on your phone.",
	"Let someone go through your YouTube history and read it out loud.",
	"Whisper a secret to the person on your left.",
	"Show the most embarrassing photo on your phone.",
	"Reply something controversial to the first Instagram stories on your timeline",
	"Call a random contact and sing “Twinkle, Twinkle, Little Star” to them.",
	"Let someone draw a tattoo on you with a marker.",
	"Let someone post anything they want on your instagram or tiktok.",
	"Show your google search history.",
	"Let someone text anyone from your contacts and they can write whatever they want.",
	"Like 20 pictures of your ex's instagram posts.",
	"Call your mom and tell her you want to be a dog.",
	"Let someone in the group read the last text message you sent out loud.",
	"Text your ex “I miss you” and don't explain.",
	"Do your worst celebrity impression right now.",
	"Let someone go through your camera roll for 10 seconds.",
	"Read your last 3 texts out loud.",
	"Text your crush ‘we need to talk’... then put your phone face down for 10 minutes.",
	"Post an unhinged (but vague) message on your story like: “I can't keep this a secret any longer...”",
	"Text your crush “It's done. The body is buried.” and don't reply for 10 minutes.",
	"Speak only in meows or barks for the next 3 minutes.",
	"Change your status to ‘Looking for trouble’ and leave it for an hour.",
	"Call your crush and ask if they're jealous of your ex, right now.",
	"Call a friend and confess something you've been hiding from them, but in a song",
	"Let someone else go through your phone for one minute, no limits.",
	"Let the group choose an embarrassing outfit for you to wear for the next hour.",
	"Let the group choose an embarrassing status for you to post for an hour",
	"Post a selfie with the caption ‘Convince me not to delete this.’",
	"Speak in a movie-trailer voice until your next turn.",
	"Balance a book or another light, unbreakable object on your head for 30 seconds.",
	"Perform three animal impressions and let the group guess each one.",
	"Invent a handshake with a willing player.",
	"Give a dramatic reading of the label on the nearest snack or drink.",
	"Freeze like a statue until the next player finishes their turn.",
	"Do a runway walk across the room using the silliest pose you can invent.",
	"Sing one chorus in an opera voice.",
	"Tell your corniest joke with a completely serious face.",
	"Draw a self-portrait with your eyes closed in 30 seconds.",
	"Let the group give you a harmless nickname for the next three rounds.",
	"Act out an emoji chosen by the group without making a sound.",
	"Perform a 20-second air-guitar solo.",
	"Spell your first name using only body movements.",
	"Mime a household chore until someone guesses it.",
	"Give a 30-second acceptance speech for “Most Dramatic Player.”",
	"Avoid saying the letter E until your next turn.",
	"Give every player a sincere compliment in five words or fewer.",
	"Silently recreate a famous movie scene until someone guesses it.",
	"Make a 20-second commercial for a harmless object in the room.",
	"Balance a spoon on your nose for 15 seconds.",
	"Tell a story that includes five words chosen by the group.",
	"Draw an animal with your non-dominant hand and let the group guess it.",
	"Create a four-line rap about this game.",
	"Mime crossing a finish line in slow motion from where you are.",
	"Keep a straight face for 30 seconds while the group tries to make you laugh without touching you.",
	"Narrate your own actions like a wildlife documentary until your next turn.",
	"Answer the next question entirely in rhyme.",
	"Pretend you are royalty and address the group for 30 seconds.",
	"Perform a weather report about the room.",
	"Make sound effects for a willing player as they take five steps.",
	"Invent one silly dance move and teach it to the group.",
	"Act like the floor is lava for 15 seconds without climbing on furniture.",
	"Move and speak like a robot until your next turn.",
	"Say the alphabet backward as far as you can in 20 seconds.",
	"Give each player a respectful superhero name and power.",
	"Give a passionate 30-second speech about why forks are better than spoons.",
	"Speak only in questions until your next turn.",
	"Pose as a museum statue and let the group name the artwork.",
	"Sing your favorite meal order like a dramatic ballad.",
	"Use your non-dominant hand for ordinary tasks until your next turn, where practical.",
	"Stack three light, unbreakable objects in 30 seconds.",
	"Act out missing a bus without speaking.",
	"Interview your imaginary alter ego for 30 seconds.",
	"Make a tongue twister from your first name and say it three times.",
	"Describe a favorite movie without its title or character names until someone guesses it.",
	"Mirror a willing player's movements for 20 seconds.",
	"Give your best villain laugh, then say a normal sentence without laughing.",
	"Sketch a mascot for the group in 45 seconds.",
	"Make a superhero entrance with an imaginary cape.",
	"Pretend to have a phone call with yourself ten years in the future.",
	"Speak like a pirate until your next turn.",
	"Perform five exaggerated facial expressions chosen by the group.",
	"Create a short rhythm by clapping or tapping and have the group repeat it.",
	"Spell a word chosen by the group backward.",
	"Make a shadow puppet and let the group guess what it is.",
	"Act out your morning routine in 20 seconds.",
	"Introduce the player to your right as a fantasy hero with a respectful title.",
	"Reenact your last trip to a shop as a silent action movie.",
	"Make up a two-line theme song for the player chosen by the group.",
	"Give a 20-second cooking-show demonstration using an imaginary ingredient.",
	"Make up a new holiday and explain its strangest tradition.",
	"Speak as if everything is breaking news until your next turn.",
	"Create a slogan for the group and lead everyone in saying it once.",
	"Explain how to make toast as if you are directing a space mission.",
	"Train an imaginary pet to do one impressive trick.",
	"Give sports commentary while a willing player performs an ordinary action.",
	"Describe your favorite color without naming it until someone guesses it.",
	"Invent a new word, define it, and use it in a sentence.",
	"Give a motivational speech to an object that has given up.",
	"Act as a tour guide for the room for 30 seconds.",
	"Retell your day in reverse order in 30 seconds.",
	"Give yourself a secret-agent codename and explain your signature gadget.",
	GO_HOME_DARE,
	DARE_ANYONE_HOME,
];

const naughtyTruth = [
	"What do you think is more important to a relationship: sex or romance?",
	"What's a weird kink or fantasy you've never told anyone?",
	"What's one secret turn-on you've never admitted to anyone?",
	"What's the most risqué place you've ever fantasized about being intimate?",
];

const naughtyDare = [
	"Ask the willing adult to your right where they would like a kiss, then give one only if they say yes.",
	"Twerk for 30 seconds.",
	"Write down one naughty thing you'd like a consenting adult partner to do tonight, then let the group guess.",
	"Role-play instant chemistry with a willing adult for 30 seconds, keeping it fully clothed and using only agreed contact.",
	"Try to seduce a chair like it's your celebrity crush — 30 seconds minimum.",
	"Give the group your slowest lip bite and most shameless wink.",
	"With permission, whisper your dirtiest fantasy to the willing adult next to you.",
	"Read the most innocent sentence you can find while holding eye contact with a willing adult.",
	"With permission, whisper one line of dirty talk into a willing adult's ear.",
	"Exchange one item of outer clothing with a willing adult for the next round.",
	"Do your best seductive dance for 30 seconds.",
	"Hold eye contact with another willing adult for 20 seconds while wearing your most mischievous smile.",
	"Deliver your boldest pickup line to another willing adult from one arm's length away.",
	"Let the group choose an innocent word and say it in the most seductive way you can.",
	"Give another willing adult a sincere compliment designed to make them blush.",
	"Strike a fully clothed pose for an imaginary after-dark magazine cover.",
	"Make a 20-second slow-motion entrance as if you are arriving at a secret rendezvous.",
	"Act out instant chemistry on an imaginary first date with another willing adult; no touching.",
	"Show the group your best “come closer” look for five seconds.",
	"Ask a willing adult to choose a hand kiss, blown kiss, or dramatic bow; make contact only if you both agree.",
	"Give a willing adult a 20-second fully clothed lap dance, with no contact unless you both explicitly agree.",
	"Remove one outer layer if comfortable, or keep it on and give the group a daring pose instead.",
	"Type a shamelessly flirty message you would never send, then read it aloud without sending it.",
	"Act out how you would invite someone back to your place without using words.",
	"Trade three increasingly bold compliments with a willing adult; either of you may stop at any time.",
	"Deliver a naughty toast to bad decisions and irresistible chemistry.",
	"Say “You should probably stop looking at me like that” without laughing.",
	"Show how you would greet a secret lover at a hotel door; stop before touching anyone.",
	"Pretend to leave a 15-second voice note inviting an imaginary crush to a midnight date.",
	"Describe a dream date that ends at the front door, then announce “cut to black.”",
	"Say “I've been thinking about you all day” in three different seductive tones.",
	"Give another willing adult a wink, slow smile, or lip bite; let them choose which.",
	"Recreate a dramatic romance-novel cover with a willing adult, fully clothed and using only agreed contact.",
	"Give a willing adult a 15-second shoulder massage over clothing after they opt in.",
	"Let a willing adult trace one word on your forearm with a fingertip and guess it, or choose an air trace with no contact.",
	"Ask a willing adult “Do you want me closer?” and follow their answer exactly.",
	"Perform a 15-second fully clothed striptease using only imaginary clothing.",
	"Do your best morning-after walk of confidence across the room.",
	"Choose a safe word for this round, then work it into your flirtiest one-liner.",
	"Recreate the moment just before a kiss with a willing adult, stopping at least a hand's width apart and breaking the pose whenever either of you wants.",
];

export const CURATED_PROMPTS = Object.freeze({
	photos: Object.freeze({
		truth: Object.freeze(truth),
		dare: Object.freeze(dare),
	}),
	naughty: Object.freeze({
		truth: Object.freeze(naughtyTruth),
		dare: Object.freeze(naughtyDare),
	}),
});
